### ISSUE TITLE
How to get the semantic segmentation prediction when using a model?

### ISSUE THREAD

**Issue by Starlento** [facebookresearch/detectron2#1212]
## ❓ How to get the semantic segmentation prediction when using a model?
According to https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
There should be outputs["sem_seg"]. But I can only find "instances".
![image](https://user-images.githubusercontent.com/33574105/79239921-b6ceda00-7ea3-11ea-94de-aa95ab48b765.png)

**Comment by pvtien96** [comment]
I think you can treat all these instances as an unique semantic segmentation. Maybe #200 helps, have a try.

**Comment by Starlento** [comment]
> I think you can treat all these instances as an unique semantic segmentation. Maybe #200 helps, have a try.

My question is not about training.
I just want to ask why my outputs don't have other fields written in the document except "instances". I hope I can get an answer about whether I use a wrong model/parameter/predictor/cfg or the document is out of date: there is not such fields.

**Comment by pvtien96** [comment]
I just want to ask why my outputs don't have other fields written in the document except "instances". I hope I can get an answer about whether I use a wrong model/parameter/predictor/cfg or the document is out of date: there is not such fields.
I think you got only "instances'' because you used the cfg= configs/COCO-InstanceSegmentation.
The outputs["sem_seg"] is only available when your model is trained using semantic segmentation config.
Also, the doc says:
"Based on the tasks the model is doing, each dict may contain the following fields:"
BTW, in case you need semantic, just trained model as I recommend in the above comment.
Hope this helps.

**Comment by Starlento** [comment]
> I just want to ask why my outputs don't have other fields written in the document except "instances". I hope I can get an answer about whether I use a wrong model/parameter/predictor/cfg or the document is out of date: there is not such fields.
> I think you got only "instances'' because you used the cfg= configs/COCO-InstanceSegmentation.
> The outputs["sem_seg"] is only available when your model is trained using semantic segmentation config.
> Also, the doc says:
> "Based on the tasks the model is doing, each dict may contain the following fields:"
> BTW, in case you need semantic, just trained model as I recommend in the above comment.
> Hope this helps.

Thank you very much :)
