### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by Ilbotre** [facebookresearch/detectron2#1269]
I'm trying to tune the hyper parameters of my detectron2 model with something as:

for param1 in params1:
   for param2 in params2:
      ... : 
             # Build a trainer from the specified config
            trainer = Trainer(cfg, run_number)
            
            # If resume==True, and last checkpoint exists, resume from it.
            # Otherwise, load a model specified by the config.
            trainer.resume_or_load(resume=False)
            
            # Start training
            trainer.train()

            results = evaluate_model_on_dataset(cfg, config_path, "flir_train",
                                                "flir_val", dataset_val_dicts )
            
            results_list.append(results)

where the params in object are new configs according to the config node in order to check out the results with differnt net architectures. The problem is the following:
the fist train goes without problems, while the second one start from the iteration where the first training ended. I would like to restart again from iteration zero. I've tried to comment trainer.resume_or_load(resume=False) but unstable behaviour were found from the SGD.
Whats is your advice?

Thanks in advance

**Comment by ppwwyyxx** [comment]
> while the second one start from the iteration where the first training ended

This should not happen because according to [the docs](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load), only the model specified by the config will be loaded by your code.

If you thin otherwise, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
