### ISSUE TITLE
Faster RCNN using resnet18 backbone

### ISSUE THREAD

**Issue by nmoutinho** [facebookresearch/detectron2#129]
## 🚀 Feature
I would like to extend resnet.py to use resnet18 backbone. 

## Motivation 
I would like to have a smaller/faster model for Faster RCNN. At the moment the smaller/faster available model is the one using resnet50 backbone. 

## Pitch
To extend the resnet backbone class to resnet18 and make pre-trained models available (e.g. for Coco-Detection -> faster_rcnn_R_18_FPN)

Thank you.

**Comment by ppwwyyxx** [comment]
ResNet18 detectors is not commonly used in research and is not considered efficient for production. So it doesn't seem to add much value to detectron2.
You can add custom backbones following https://detectron2.readthedocs.io/tutorials/write-models.html.

**Comment by SteveTsui** [comment]
have u get the results if faster rcnn via resnet18 on COCO?

**Comment by ppwwyyxx** [comment]
ResNet18/34 are supported in 86c95ab9647d64dbcc6f89965cba17bedbaa2e82, though we don't plan to add pretrained models for reasons mentioned above.

**Comment by ASKanse** [comment]
The changes in [86c95ab](https://github.com/facebookresearch/detectron2/commit/86c95ab9647d64dbcc6f89965cba17bedbaa2e82) are not reflected int the wheel files present in the colab notebook for installation of detectron2.
When will the ResNet 18/34 be added to the wheel file so that we can use it in the Google colab Notebook?
Or should I manually change the code in file according to the changes?

**Comment by ZachNew** [comment]
@ppwwyyxx just came across this while wondering about using a resnet18 as a backbone. Do you have a reference for the claim about them not being used in production? Not looking to dispute it, just interested in the analysis.
