### ISSUE TITLE
why Inference Demo with Colab trained Models detected 0 instances

### ISSUE THREAD

**Issue by sswhqqw** [facebookresearch/detectron2#1417]
When I used command:
python demo/demo.py  \
    --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --input /Users/wenzq/Downloads/detectron2/demo/horseface01601.jpg --output outputs/ \
    --opts MODEL.WEIGHTS '/Users/wenzq/Downloads/detectron2/train_model/model_final_f10217.pkl' \
     MODEL.DEVICE cpu
result in :
detected 3 instances
<img width="1439" alt="屏幕快照 2020-05-13 下午8 24 44" src="https://user-images.githubusercontent.com/35377837/81812480-c439bb80-9558-11ea-89fe-977a7b76084a.png">
![horseface01601](https://user-images.githubusercontent.com/35377837/81812497-cac83300-9558-11ea-8f41-09d3242d3497.jpg)
note:
     model_final_f10217.pkl is the  model Pre-trained Models

When I used command:
python demo/demo.py  \
    --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --input /Users/wenzq/Downloads/detectron2/demo/horseface01601.jpg --output outputs/ \
    --opts MODEL.WEIGHTS '/Users/wenzq/Downloads/detectron2/train_model/model_final-3.pth' \
     MODEL.DEVICE cpu
detected 0 instances
<img width="1435" alt="屏幕快照 2020-05-13 下午8 38 15" src="https://user-images.githubusercontent.com/35377837/81813289-d9fbb080-9559-11ea-8b0a-40b1d21da780.png">
![horseface01601](https://user-images.githubusercontent.com/35377837/81813303-dff19180-9559-11ea-8904-f58a69baa7cc.jpg)

note:
     model_final-3.pth is the  model trained on colab which can predict instance nomally on colab.

**Comment by davidmurray** [comment]
I'm also getting a similar issue.

`python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input C:\Users\dmurray\code\analyses_images\assets\man-horse.jpg --confidence-threshold 0.1 --opts MODEL.DEVICE cpu`

**Note**: I am running on CPU because I do not have a GPU.

(The image 'man-horse.jpg' is the following: http://images.cocodataset.org/val2017/000000439715.jpg)

Attached is the output when running demo.py:
[output.txt](https://github.com/facebookresearch/detectron2/files/4623084/output.txt)

# Versions
Torch: 1.5.0
detectron2: 0.1.2

Thanks.

**Comment by davidmurray** [comment]
Quick update:

Here is what I get when I run the following command:

`python .\social_distancing\inference\inference.py --config-file COCO-Detection\faster_rcnn_R_50_C4_1x.yaml --image-input C:\Users\dmurray\code\analyses_images\assets\man-horse.jpg --confidence-threshold 0.1`

Could it be because the image is not being loaded properly?

Note: I understand that detectron2 is not officially supported on Windows, but I have managed to get it to compile, so I am wondering why inference is not working.

<img width="960" alt="image-not-working" src="https://user-images.githubusercontent.com/545502/81837399-cf69f880-9512-11ea-82c0-4146c623c47e.PNG">

Thanks,
David

**Comment by davidmurray** [comment]
**Update**: I fixed my problem. I was setting `MODEL_WEIGHTS` rather than `MODEL.WEIGHTS` on the config object.

**Comment by ppwwyyxx** [comment]
When loading the model for inference you need the same config, same number of classes, etc.

Also, as the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
