### ISSUE TITLE
why does detectron2  train so fast?

### ISSUE THREAD

**Issue by FanShuixing** [facebookresearch/detectron2#142]
Hello! Thanks for your sharing for this excellent work.
I have used detectron2 to tain mask rcnn with custom datasets ,it works well. I just can't understand why does detectron2 train so fast, could you give me some advice to let me figure out this question?
Looking forward to your reply.

**Comment by ppwwyyxx** [comment]
If you ask why Detectron1 is slower, then we know it's because of the CPU ops. But I don't remember adding anything to detectron2 that significantly improves its speed. It was about the current speed from the beginning of the project. After all, maskrcnn-benchmark is already quite carefully written for speed.

I wouldn't say it's "so fast" since there are still many ways to make it faster. Nvidia experts have done some optimizations on mask rcnn that we might want to include. And [aws-samples/mask-rcnn-tensorflow](https://github.com/aws-samples/mask-rcnn-tensorflow) also claims faster speed than detectron2 (it's also based on my code).

**Comment by FanShuixing** [comment]
Thanks.
