### ISSUE TITLE
cannot import name '_C'

### ISSUE THREAD

**Issue by lwihtittlee** [facebookresearch/detectron2#157]
When I run a demo or a test project, it keeps showing up.
"from detectron2 import _C"   Importerror: cannot import name '_C' "
How can I resolve the error?

**Comment by ppwwyyxx** [comment]
You did not build detectron2. Please install it following [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md)

**Comment by jas-nat** [comment]
I have the same problem. However, I have followed the installation steps using "pip3 install build develop". 

The errors: Failed to load OpenCL runtime
Traceback (most recent call last):
  File "Copy_of_Detectron2_Tutorial custom.py", line 49, in <module>
    from detectron2.engine import DefaultPredictor
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/engine/hooks.py", line 17, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesEvaluator
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/evaluation/cityscapes_evaluation.py", line 10, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/data/build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/structures/boxes.py", line 7, in <module>
    from detectron2.layers import cat
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/dlsj/Documents/Detectron2/detectron2_repo/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: cannot import name '_C'

Environment:
Ubuntu 18.04.03 LTS
Python 3.6.8
GCC 7.4.0
Pytorch 1.3.0
OpenCV 3.2.0

**Comment by ppwwyyxx** [comment]
> However, I have followed the installation steps using "pip3 install build develop".

The installation instructions are not like this.

**Comment by ekorudiawan** [comment]
Same issue, after build detectron2 with:

```bash
python setup.py build develop
```
and try to run with:

```bash
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.jpg input2.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

Got an error:
```bash
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/eko_rudiawan/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/eko_rudiawan/detectron2/detectron2/data/build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "/home/eko_rudiawan/detectron2/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/eko_rudiawan/detectron2/detectron2/structures/boxes.py", line 8, in <module>
    from detectron2.layers import cat
  File "/home/eko_rudiawan/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/eko_rudiawan/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/eko_rudiawan/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```
I am using anaconda env
Python: 3.7.3
Torch: 1.3.1
Torchvision: 0.4.2

**Comment by ppwwyyxx** [comment]
That's not the same issue because your error does not contain "cannot import name '_C'".

Please see if the information https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues resolves your issue. If not, please provide an environment so that your issue can be reproduced by other people.

**Comment by riven314** [comment]
@ekorudiawan 
I encountered the same error before 
```
ImportError: /home/eko_rudiawan/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

The following procedures solve my problems:  
1. uninstall conda env and gcc build by the following command:  
```
$ conda remove --name your_conda_name --all
detectron2$ rm -rf build
detectron2$ rm -rf **/**.so
```

2. update base conda:  
```
$ conda update -n base -c defaults conda
``` 

3. update conda's libgcc:
```
$ conda update libgcc
```

4. reinstall conda environment and build detectron2, as instructed in [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/dcdde67381489c73a035ac6b4e86a402ae0dcbcf/INSTALL.md)

P.S. the above steps are actually from INSTALL.md.

**Comment by k-miracle** [comment]
I've met the same issue, but I can run `import detectron2`, so what's the problem?

**Comment by ekorudiawan** [comment]
I am not sure, in my case, I installed multiple GCC version on my computer, then I try to recompile with GCC 7 and it's work

**Comment by kubapok** [comment]
If you install by pip, and run demo or example in git repo detectron in root directory, `import detectron` may import lib from your git root directory (not pip installation). This won't work (you want to use pip installation).

You may remove detectron directory or change the name, so python will look in pip packages.

**Comment by victoriasyp** [comment]
> I've met the same issue, but I can run `import detectron2`, so what's the problem?

yes, I have met the same problem. You should change the floder name "detectron"

**Comment by amjindal** [comment]
i'm facing this issue on google colab. From last 2 months i'm running the same code but today i start facing this issue.
i install dependencies like this way

# install dependencies: (use cu101 because colab has CUDA 10.1)
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install cython pyyaml==5.1
!pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())
!gcc --version
# opencv is pre-installed on colab
# install detectron2:
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html


and then i i just import the libraries
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import cv2
import random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
from detectron2.data.catalog import DatasetCatalog

and i got the following error

ImportError: /usr/local/lib/python3.6/dist-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

**Comment by maisonhai3** [comment]
I got the exact same problem.

Just an action of rename will help our soul.

Suppose we are in `experiment` folder, after git clone `detectron2`, we have:

experiment   
 |--- detectron2  
 |---|--- configs  
 |---|--- datasets  
 |---|--- detectron2


**The why**:
Suppose we want to run `/experiment/detectron2/demo/demo.py`, 
The error of `cannot import name '_C'` will appear.
As `demo.py` try to import `detectron2` from the folder of `detectron2/detectron2`,
Instead of importing from this folder instead of our Detectron2 installation somewhere else.

Take a look at `detectron2/detectron2`, there is a `__init.py__`, which causes this mistake.


**Solution**:
Rename `detectron2/detectron2` to example `detectron2/detectron2_you_make_me_trouble`

**Comment by rohitdileep** [comment]
i had solved the issue by downloading the following packages.
! git clone https://github.com/facebookresearch/detectron2.git detectron_repo
! pip install -q -e detectron_repo
! pip instal pyyaml==5.1
! pip install omegaconf==2.1.0.dev26

**Comment by GrantorShadow** [comment]
> If you install by pip, and run demo or example in git repo detectron in root directory, `import detectron` may import lib from your git root directory (not pip installation). This won't work (you want to use pip installation).
> 
> You may remove detectron directory or change the name, so python will look in pip packages.

For those who didn't get this, Please rename the folder inside the CenterNet2 named as detectron2 as detectron2__ or anything else for pip to index the detectron folder. Hope this helps
