### ISSUE TITLE
Detectron CVPR claim

### ISSUE THREAD

**Issue by bluesky314** [facebookresearch/detectron2#1646]
It was said in the Detectron CVPR Tutorial that many papers may claim they are faster and more accurate than the original Faster RCNN but the library is continually updated and currently more faster and accurate due to various optimizations. 
Here is the screenshot of the slide: 
![Screen Shot 2020-06-16 at 12 27 45 AM](https://user-images.githubusercontent.com/35393972/85208254-6add5d00-b34c-11ea-96f7-b5f0b189bba2.png)

May we know what some of these optimizations for speed and accuracy are so we can better judge such claims?

**Comment by ppwwyyxx** [comment]
I think a large part of it comes from using pytorch, using better GPUs, and train longer with augmentation.

The focus is not about a specific architecture (Faster R-CNN), because every point will shift a lot with these changes. The goal of the slide is to remind that these details have a big impact, so should be paid more attention to when making comparisons.

btw, I forgot to put a link but this slide originally came from https://www.dropbox.com/s/6izllk62dobao9n/ICCV19_generalized_rcnn_tutorial_ross_girshick.pptx?dl=0#
