### ISSUE TITLE
Is there way to split dataset?

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1703]
In Keras we have very convenient way of splitting one dataset to train/val

Is there exists something similar while coco registering?

**Comment by ppwwyyxx** [comment]
It can be easily implemeted with https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by chiboreache** [comment]
> It can be easily implemented with [detectron2.readthedocs.io/tutorials/datasets.html](https://detectron2.readthedocs.io/tutorials/datasets.html)

ctrl+f 'split' -> give me nothing!

why you closing the issue before giving correct answer!?

**Comment by ppwwyyxx** [comment]
The documentation explains how to use *any* dataset. Therefore it includes how to use a split of a dataset, as long as the "split" is implemented.

**Comment by chiboreache** [comment]
> The documentation explains how to use _any_ dataset. Therefore it includes how to use a split of a dataset, as long as the "split" is implemented.

nevermind, i already done it with `from sklearn.model_selection import train_test_split` 

just in case - official docs are useless, that's why i and many others, opens _How to do something?_ issues here

not for redirecting us to official useless docs without proper instructions

hope you understand.

**Comment by ppwwyyxx** [comment]
The documentation explains how to add the split dataset after using ` from sklearn.model_selection import train_test_split`, so it is apparently useful to your issue.

Because how to perform the actual spliting is trivial to implement within a few lines of code (or one line with sklearn), I wrongly assumed that it is not what you're asking.
It might have been more clear if questions can be asked following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=questions-help-support.md), namely:
> Describe what you want to do, including:
   what inputs you will provide, if any:
   what outputs you are expecting:

**Comment by doursand** [comment]
@chiboreache I was looking for the exact same thing & I even didn't think about the train_test_split , so thanks for the tip ;-)

**Comment by chiboreache** [comment]
> I was looking for the exact same thing & I even didn't think about the train_test_split , so thanks for the tip ;-)

you welcome) 

at the first time when i saw how literally every tutorial doing hot encoding by hand i was confused, so i decided to go deeper and finally found nice and dandy way :P
