### ISSUE TITLE
Add option for different class probabilities in pred_classes

### ISSUE THREAD

**Issue by j-adamczyk** [facebookresearch/detectron2#1754]
## 🚀 Feature
Add option to Predictor to output probabilities of all classes, not only the most probable class. In other words, make `scores` field in output a 2D tensor, instead of 1D while appropriate option is used.

## Motivation & Examples

Often similar objects get high probabilities, while from domain knowledge we know that some classes are less probable. If the `scores` was a 2D tensor with probabilities for different classes, manual filtering and thresholding would be possible. This would be mostly useful in the real production environment.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model explains ways to obtain intermediate tensors during the computation.

There are __hundreds of__ intermediate tensors during the computation. Despite probabilities might seem more "special" than others, in general it doesn't seem to be a good idea to add options to retrieve those intermediate tensors.

**Comment by j-adamczyk** [comment]
@ppwwyyxx yes, probabilities *are* more special than others. They do seem like that, yes, simply because they are. Intermediate tensors provide internal information about the model, while object class probabilities are literally output of the model, not it's internal work. It could be argued that returning sorted class probabilities should even be default be default behaviour, since it's basic information that model gives us. This particular option is widely supported in machine learning frameworks - in fact I was really surprised when I couldn't find easily accessible option for this in Detectron. While I agree that exposing internal tensors should be left for individual users, such basic option like class probabilities should be easily accessible option.

**Comment by ppwwyyxx** [comment]
The option can exist in other machine learning frameworks/models mainly because they don't do object detection.

For object detection models, it's even unclear what it means to "return probabilities". Not all models will compute probabilities in a way you might expect. And as a result, it would make no sense to make it default, and adding an option would require first properly defining what should be returned by such option, and assuming that all detection models are able to compute it.

It might make sense for object detection models, to have an option that let it return "raw outputs" from which some notion of probability might be derived in a model-specific way. But this will be different for each model, and it typically takes a sequence of complicated operations (e.g. https://github.com/facebookresearch/detectron2/blob/b88c6c06563e4db1139aafbd6d8d97d1fa7a57e4/detectron2/modeling/roi_heads/fast_rcnn.py#L81-L128) to make use of these raw outputs. So it doesn't seem to add much value to the existing approach in https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model

**Comment by j-adamczyk** [comment]
The existing object segmentation models output final class probability anyway, which is even plotted by default on images. This probability is more of a model confidence measure in %, but nevertheless it should have an option to provide scores for all classes. After all, if the difference between first and second place in terms of this confidence is small or large is important information about the object itself. It has to be calculated anyway, since later max value is chosen, so implementing an option should be easy enough to be a viable enchancement.

**Comment by ppwwyyxx** [comment]
If you mean semantic segmentation models, probabilities can be easily defined on them. What I meant is for "bounding box" detection models, probabilities are not defined.

I agree that it is useful. I'm only pointing out that given it's not well defined and different in each model, it may not worth designing an option for it. 

> It has to be calculated anyway, since later max value is chosen

That is not true for many (in fact, all in detectron2) bounding box detection models. The code pasted above is an example. No probabilities are calculated and no maximum operation happens.

> Of course it can be implemented by hand ...

Some implementation that helps compute probabilities (if defined properly first about what it does) can have value to be added in detectron2, and then used by users. I'm only pointing out that adding it as an option of the model is not a most reasonable thing to do.

**Comment by j-adamczyk** [comment]
I actually meant instance segmentation, but now I see your point. I'll try to implement it myself and publish code on this.

**Comment by ppwwyyxx** [comment]
Mask R-CNN uses the function in https://github.com/facebookresearch/detectron2/issues/1754#issuecomment-658636511 to compute `pred_classes`. The second output of the function is some indices which can be used to index the input `scores` to obtain scores for each class. This is one notion of probability that's easiest to implement, although one can argue for other more complicated approaches such as running `box_predictor` again for the predicted boxes.

**Comment by j-adamczyk** [comment]
Thank you for the explanation! This question now appears as first result in Google for many queries on this, so this should help others too.
