### ISSUE TITLE
Class-Incremental Training for saving training time

### ISSUE THREAD

**Issue by rose-jinyang** [facebookresearch/detectron2#1808]
Hello
How are you?
Thanks for contributing this project.
I have a question.
Does this project support class-incremental training for saving training time?
Let's suppose I've trained a 2D object detection model on the dataset with K classes for 5 days.
If a new class is added into this dataset, should we train a model with the expanded dataset (K+1 classes) from begin?
If so, it is so expensive, especially in case of object detection in retail store.
That's because a new class of good is added frequently in retail store.
Can we train a new model in short time with the original weight on the expanded dataset?
I think that this is very important function.
Please let me know if you have a willing to implement this.
Thanks

**Comment by jalbarracinv** [comment]
Hi!  I was going to make the exact same question. Really need to know if this can be done.

**Comment by ppwwyyxx** [comment]
How to do this is more of a machine learning question / research question rather than a detectron2 question, since the answer to "what to do" (like re-train from the beginning) is unlikely to be specific to detectron2 in any way. If you have decided what to do, but not sure how to use detectron2 to do it, then it may become something we can help with.

**Comment by jalbarracinv** [comment]
I have trained a model with 171 classes. It took several hours. Now I want to add one class. Can I add a new class without training again the 171 classes?
