### ISSUE TITLE
Multi-GPU DefaultTrainer, evaluation metrics incorrect

### ISSUE THREAD

**Issue by ezekielbarnett** [facebookresearch/detectron2#1838]
Summary: I am getting much lower AP stats on evaluation using multi-gpu training vs single gpu. How can I get accurate mAP stats for evaluation hooks while training on multi-gpu?

I am training a generic object detection model (faster-rcnn) with Detectron2 roughly following the format of the colab tutorial, using a custom dataset and the COCOEvaluator to do the evaluation within the training hooks, i.e.:

```
class Trainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=CustomDatasetMapper(cfg, True))

    @classmethod
    def build_evaluator(cls, cfg, dataset_name='custom_dataset_val'):
        return COCOEvaluator(dataset_name, cfg, False, output_dir=cfg.OUTPUT_DIR)
```

I launch the training following the tutorial:

```
    launch(train,
               args.num_gpus,
               num_machines = 1,
               dist_url = args.dist_url,
               args = (args,))
```

When I train on multiple GPUs  the evaluation returns much lower AP metrics compared to single-GPU training on the same  iteration. 

Furthermore, after training the model on the same data for N iterations with either multi- or single-GPU (with the same hyperparams, scaling the LR and batch size), separate evaluation with a single GPU of the models on the validation split achieves roughly the same AP statistics.

My hypothesis is that some of the logic for computing these evaluation metrics during training is either 1) incorrectly implemented for multi-gpu, 2) I am missing some important configs / params for the multi-gpu case with the COCOEvaluator.

**Comment by ppwwyyxx** [comment]
Since we do not know what exactly you did/changed/observed, we cannot tell whether your expectation about AP is reasonable.  If you can include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose), maybe there are more to tell.

Also, I believe `COCOEvalautor(distributed=True)` should be used according to https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.COCOEvaluator
