### ISSUE TITLE
AttributeError: 'GroupedBatchSampler' object has no attribute 'drop_last'

### ISSUE THREAD

**Issue by wangg12** [facebookresearch/detectron2#186]
Hi, I tried to obtain the length of the `train dataloader` returned by `build_detection_train_loader`, but got this error. 
Is it an expected behavor? How can I correctly obtain the length of the `train dataloader`?

**Comment by ppwwyyxx** [comment]
The training data loader in general does not have length.

**Comment by wangg12** [comment]
I see. But I think the bug is due to the `GroupedBatchSampler` inherited from `BatchSampler` has no attribute `drop_last`, which will cause error in the `__len__` of `BatchSampler`. 

Can I simply implement a `__len__` method for `GroupedBatchSampler` by `len(self.sampler) // self.batch_size`?

**Comment by ppwwyyxx** [comment]
`len(self.sampler) // self.batch_size` may not be correct because the actual size in the end depend on how the samples are grouped and may even be different each time it is iterated through.

That's why it's in general a bad idea to expect training dataset has a "size". 
But indeed the current error message is confusing. It would be an improvement to raise a more proper error message in `__len__` rather than inheriting the parent class.
