### ISSUE TITLE
Is it able to draw panoptic segmentation from the data dict?

### ISSUE THREAD

**Issue by ge-li** [facebookresearch/detectron2#211]
The draw_dataset_dict() doesn't use the **thing_dataset_id_to_contiguous_id, stuff_dataset_id_to_contiguous_id**. 

And the draw_panoptic_seg_predictions() only supports drawing panoptic segmentation results. 

If possible, could you please add a minimal example for training panoptic segmentation in the colab notebook for reference?

Thank you very much!

**Comment by ppwwyyxx** [comment]
We can't draw panoptic segmentation in dataset dict because the dataset dict doesn't have panoptic segmentation annotations: due to how the PanopticFPN model works, it only uses separate instance & semantic segmentation annotations.

We may add support for true panoptic segmentation annotations when a use case appears in the future.

**Comment by tom-bu** [comment]
I had a quick question. In the separate semantic segmentation annotation, should the 0 ID, which represents things, be ignored during training? Or should the "thing" ID also be learned?
