### ISSUE TITLE
conversion of detecron2 (.pth) custom trained model to onnx format or .pb format

### ISSUE THREAD

**Issue by akashAD98** [facebookresearch/detectron2#2129]
I am using detectron2 model for instant segmentation & object detection .My goal is to deploy this model on cpu or android /ios device (, But model size is large. So i want to convert (.pth) model into light weighted model

I need a script (written in Python) that would take a trained PyTorch model file (*.pth extension) and export it to TensorFlow format (*.pb). [frozen graph] or .onnx 
so i can use this for tensorflowlite

The model was trained using the Facebook's DETECTRON2  (the pre-trained model was "faster_rcnn_R_50_FPN_1x")

I already have the output "*pth" file. The script should take this file as a parameter and return single '*.pb' file.

i checked onnx repo but there is not any clear code or documents (its available for cnn conversion) ,hope you will provide solution.

**Comment by ppwwyyxx** [comment]
> I need a script (written in Python) that would take a trained PyTorch model file (.pth extension) and export it to TensorFlow format (.pb). [frozen graph] or .onnx

It is impossible because the .pth file does not contain model structure.

https://detectron2.readthedocs.io/tutorials/deployment.html has instructions for onnx conversion.
https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2 has instructions for tensorflow conversion. I don't think either will run on tflite because tflite lacks many ops.
