### ISSUE TITLE
Confused about coordinate system of Detectron2

### ISSUE THREAD

**Issue by myaldiz** [facebookresearch/detectron2#2401]
Hello everyone!

I am trying to understand the coordinate system used for detectron2 (wrt OpenCV), but could not find a place that includes all the information in a detailed way. I really appreciate your explanations!

- From what I understand, bounding box coordinates are in the range of `[0,width], [0,height]`. Does that means pixel centers are located with `0.5 offset` like `(0.5, 0.5), (1.5, 0.5), (2.5, 0.5)` and so on?
- In addition [link](https://github.com/facebookresearch/detectron2/blob/master/docs/notes/compatibility.md) says that keypoint indices are in the range of `[0, width - 1], [0, height - 1]`. Does that mean keypoint locations lie on pixel centers without any coordinate offset?
- For ROIAlignV2 pooling operation, does the detectron2 start sampling directly from a top-left corner, which corresponds to [pytorch's `align_corners=True`](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.grid_sample) option. Or does it refer to the corner point of the input’s corner pixels? And in this context does the pixel center still lies with (0.5, 0.5) offset?
-  Matplotlib (and OpenCV) uses pixel centers without an offset, does this means that when visualizing detectron2 bounding box output on matplotlib, we need to subtract (0.5,0.5) first? And same as matplotlib, for the custom datasets of OpenCV outputs, do we need to add (0.5, 0.5) to the coordinates?

Thanks!

**Comment by ppwwyyxx** [comment]
1. yes
2. Keypoints are interpreted the same as (1), but "keypoints in COCO-format annotations" are not, because COCO uses a different coordinate system.
3. "sampling directly from a top-left corner" is not very well-defined so I would prefer to not answer. But everything tries to follow `align_corners=False` and be consistent (i.e. pixel center lies with (0.5, 0.5).  There is more info here: https://github.com/facebookresearch/detectron2/blob/0d72f4397f4e49e4f7c093906600c97810079f1d/detectron2/layers/roi_align.py#L74-L92
4. > Matplotlib (and OpenCV) uses pixel centers without an offset

This is true for some functions in matplotlib/opencv but not all. It depends on what functions you're using and sometimes a conversion is needed.
