### ISSUE TITLE
Evaluating Cityscape dataset

### ISSUE THREAD

**Issue by omarfahmy** [facebookresearch/detectron2#2610]
I am trying to rub model zoo on cityscape dataset for instance segmentation. I have follow Colab tutorial for loading dataset and training, it goes ok. However, when running inference & evaluation section it predicts only one class "cars"
Could you support me how to evaluate and predict other possible classes?..

Thanks & Best Regards

**Comment by ppwwyyxx** [comment]
Please try models we provide in model zoo because we don't help users with their new models. As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

If you experience issues with pretrained models, please report using the issue template.

**Comment by omarfahmy** [comment]
I am actually using Modelzoo as in the Colab tutorial; however i change the exmple fron ballon dataset to cityscape dataset...
It gives me one predicted cluster

could you help me how to predict more cluster of cityscape dataset ?..
