### ISSUE TITLE
Correct way to access new baselines

### ISSUE THREAD

**Issue by simonsapiel** [facebookresearch/detectron2#3174]
It seems that the new baselines don't contain any yml files? There isn't documented how one can use these when training. Certainly `cfg.merge_from_file(model_zoo.get_config_file("new_baselines/mask_rcnn_regnetx_4gf_dds_FPN_100ep_LSJ.py"))`

doesn't seem to work. How should this be used?

**Comment by JohannesTheo** [comment]
With the .py configs you can simply do:

`model = model_zoo.get("new_baselines/mask_rcnn_R_50_FPN_100ep_LSJ.py")`

see [model_zoo.py#L167](https://github.com/facebookresearch/detectron2/blob/a8743cff571c2d3f032fa27d772d9dde77f16598/detectron2/model_zoo/model_zoo.py#L167)

when using the argument `trained=true` this should already load the weights. However, the urls have not been updated yet so this will result in an error for the time being. You can load them manually though using the urls from the model zoo:

```python
from detectron2.checkpoint import DetectionCheckpointer
DetectionCheckpointer(model).load(url)
```

Hope this helps :)

**Comment by skuda** [comment]
Hi, I know the issue is closed but I was trying to fine-tune on a custom dataset using the new baselines and I can't find an example to do it.

I loaded the model, its cfg and the weights using the sample @JohannesTheo posted above but I don't know how to change the dataset, the max_iter, or the other parameters because the config is of type omegaconf.DictConfig not CfgNode.

There is some related sample to train on a custom dataset starting from a .py configuration? Thanks!
