### ISSUE TITLE
 Why facebook hasn't released an official package/image/etc for detectron2?

### ISSUE THREAD

**Issue by Akshay-Ijantkar** [facebookresearch/detectron2#3287]
I can find conda package of Detectron 2 here: [Third party]
Page link here: https://anaconda.org/conda-forge/detectron2
`conda install -c conda-forge detectron2`
Latest version : 0.4.1

I can also find pip install: [Third party]
Page link here: https://pypi.org/project/geoai-detectron2/
`pip install geoai-detectron2`
Latest version: 0.4 

I do understand you have a well-documented installation guide:
https://detectron2.readthedocs.io/en/latest/tutorials/install.html 

Can you please guide me on why Facebook (I meant authors of detection 2 )haven't released an official package in Pypi or in conda? Any specific reason behind it? Are they planning to release this official package any time sooner?

Thank you in advance!

**Comment by ppwwyyxx** [comment]
We always have released official packages at https://detectron2.readthedocs.io/en/latest/tutorials/install.html#install-pre-built-detectron2-linux-only.

We don't release at Pypi because they don't allow choosing package based on cuda/torch version, like what's in the above link.

Maybe this is possible with conda but (1) seems not so easy (2) even if it's possible it would require user to use a conda-version of pytorch. So it doesn't feel worthwhile of the effort.
