### ISSUE TITLE
kernel size in LastLevelMaxPool

### ISSUE THREAD

**Issue by rakhimovv** [facebookresearch/detectron2#331]
Hi, is this a bug in LastLevelMaxPool from fpn?

`return [F.max_pool2d(x, kernel_size=1, stride=2, padding=0)]`

kernel_size=1 with stride=2 makes no sense

**Comment by ppwwyyxx** [comment]
It's correct. See paper for details.

**Comment by xmyqsh** [comment]
@rakhimovv 
It is equivalent to pool without max.
It is also equivalent to downsampling without max.

**Comment by xmyqsh** [comment]
@rakhimovv 
`LastLevelMaxPool` is used to generate p6 from p5.
It is served as a cheap cost of large anchor 512 instead of using the ancher scale config.
So, there is no need to `conv` with learnable parameters.
Also, for the non-learnable operator `maxpool`, we'd better set the kernel size to 1 which should generate the most accurate anchor proposals.

**Comment by rakhimovv** [comment]
@ppwwyyxx @xmyqsh thanks a lot
