### ISSUE TITLE
I try to reproduce the result for cityscapes

### ISSUE THREAD

**Issue by TakeruIto** [facebookresearch/detectron2#342]
I try to reproduce the result for cityscapes but result is not good.

For example, when fine&COCO training, all I need to change in config is max_iter 4000 and steps 3000, right?
And, I try to train model with 1 GPU. I think IMS_PER_BATCH is 1 and  BASE_LR is 0.00125 but GETTING_STARTED.md says 2 and 0.0025 respectively. Which is correct?

I’m sorry for my poor English and thank you a lot for your help.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says:

> If you expect the model to work better, note that we do not help you train your model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

If you cannot reproduce the results with the official config, it is a detectron2 issue and please include details following the issue template. Otherwise we'll not help with it.
