### ISSUE TITLE
Question about RoIAlign

### ISSUE THREAD

**Issue by FL77N** [facebookresearch/detectron2#3466]
Hi~I don't understand why the roi subtract 0.5 which can get better performance.Could you explain it more detailly? Thank you!

**Comment by puhuk** [comment]
Detectron2 use transform.resize function from scikit-image for grid locations and "integer corners" (half-integer centers) so the first pixel is centered at (0.5, 0.5). So it has relationship between continuous coordinates and discrete pixel indices.
coord=index+0.5
index=floor(coord)

I think that's why roi substract 0.5 for better performance.

**Comment by FL77N** [comment]
Thank you sincerely!
