### ISSUE TITLE
An import error occurs when importing detectron2

### ISSUE THREAD

**Issue by fsted** [facebookresearch/detectron2#3710]
hello,I'm a researcher who just started trying detectron2;However, when I successfully downloaded detectron2, an error occurred while using it.

I just:  from detectron2.engine import default_argument_parser, default_setup, launch
but accept an error:

"/home/tony/anaconda3/envs/detect2/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v"

some ones of environment:
torch                     1.8.0+cu101              
torchaudio                0.8.0                
torchvision               0.9.0+cu101             

What should I do, thank you

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues:

> Undefined symbols that contains TH,aten,torch,caffe2.
This usually happens when detectron2 or torchvision is not compiled with the version of PyTorch you’re running.
If the error comes from a pre-built torchvision, uninstall torchvision and pytorch and reinstall them following pytorch.org. So the versions will match.
If the error comes from a pre-built detectron2, check release notes, uninstall and reinstall the correct pre-built detectron2 that matches pytorch version.
If the error comes from detectron2 or torchvision that you built manually from source, remove files you built (build/, **/*.so) and rebuild it so it can pick up the version of pytorch currently in your environment.
If the above instructions do not resolve this problem, please provide an environment (e.g. a dockerfile) that can reproduce the issue.

Please remember to follow the issue template when creating an issue.
