### ISSUE TITLE
COCO RLE format for segmentation

### ISSUE THREAD

**Issue by DragonDuck** [facebookresearch/detectron2#408]
I'm trying to use COCO's RLE format for segmentation as it's more robust to convert our data into that than polygons. According to the [tutorial on custom datasets](https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/datasets.md), this should be possible.

However, this leads to numerous errors, starting with the data mapper and transformation. At several points in the code, polygons are the required format for segmentation annotations. Most notably in the function [detectron2.data.detection_utils.annotations_to_json](https://github.com/facebookresearch/detectron2/blob/38fedca84c9a04399149fa1bd64743c983d39ff3/detectron2/data/detection_utils.py#L214), where PolygonMasks/BitMasks are created for the modelling backend. In particular, the Bitmask, at least in this function, is generated from polygons as well.

My question: Is the RLE format _really_ supported? It's only sparsely mentioned in the code itself and it's looking like I'll have to add a substantial amount of code to my own code base to make use of this format. Is there a simple solution I'm missing?

**Comment by ppwwyyxx** [comment]
Ideally, the function `annotations_to_instances` should be able to recognize RLE and create BitMasks from it since that's trivial.
This is not implemented now and there is an open issue #200 already.

You can either implement it in your custom data loader, or implement it in detectron2 and we'll welcome a PR.

Closing as a duplicate.
