### ISSUE TITLE
Gradients of the first and second stage losses

### ISSUE THREAD

**Issue by gunshi** [facebookresearch/detectron2#447]
## ❓ Questions and Help

Hi, I had a general question, the answer to which I wasn't able to decide clearly based on thoroughly checking the source code. Does the loss from the second stage in faster-rcnn-like architectures also backprop into the first stage? Or are the losses for the two stages operating on their respective weights and not being shared across first and second stage?
Would be really helpful to get a clarification on this.. 

Thanks!
Gunshi

**Comment by ppwwyyxx** [comment]
It depends what "backprop into the first stage" mean precisely.
Since this is neither a bug report or a feature request or about how to use detectron2 I'm closing this. Github issues of detectron2 are not the place to ask how Faster R-CNN works. You can find answers by reading {,Fast,Faster} R-CNN papers.

**Comment by gunshi** [comment]
Hi @ppwwyyxx sorry about the wording, I meant specifically in the case faster-rcnn based architectures in the detectron repo.
