### ISSUE TITLE
Training with different level of supervisions

### ISSUE THREAD

**Issue by Yuliang-Zou** [facebookresearch/detectron2#45]
Suppose I have a mixture of datasets, some of them only have bbox annotations, and some of them have both bbox and mask annotations. 

I wonder what is the easiest way to train a Mask R-CNN with this mixed dataset. Should I use different dataloader for different dataset, and then modify the trainer so that it can handle each type of supervision individually?

Thanks.

**Comment by ppwwyyxx** [comment]
1. Register your dataset: https://detectron2.readthedocs.io/tutorials/datasets.html
2. The default dataloader may work for you already (if you just set polygons to an empty list for instances that do not have mask annotations). If it does not you can write a new dataloader: https://detectron2.readthedocs.io/tutorials/data_loading.html
3. Write a new `ROIHeads` so that it handles instances without mask annotations properly: https://detectron2.readthedocs.io/tutorials/models.html

**Comment by Yuliang-Zou** [comment]
Thank you so much! I will take a look at the tutorial.
