### ISSUE TITLE
Implement/Enable vertical flipping of images

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#507]
## 🚀 Feature
Implement/Enable vertical flipping of images.

## Motivation
Vertical flipping is a useful augmentation for many kinds of images. 

## Pitch
We should implement/enable vertical flipping of images. If I see it correctly, most of it should already be available (e.g. `VFlipTransform` is already implemented in fvcore). At first glance, mainly `RandomFlip` in `detectron2/data/transforms/transform.py` needs to be changed.

Are there other pieces of code that would need adaption? For instance in the `config` module?

If desired, I could try myself on Implementing it and make a PR.

**Comment by ppwwyyxx** [comment]
Adding to `RandomFlip` sounds good. We don't currently have a plan on integrating more augmentations in configs - because a config is too limited to express the augmentation space, so it only supports a few standard ones. For now we encourage users to apply more augmentations by a custom dataloader/mapper (https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader).

**Comment by maxfrei750** [comment]
Closing this, so that a unified discussion can take place in #643.
