### ISSUE TITLE
How to implement early stopping?

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#509]
## ❓ How to implement early stopping?

What would be the best place to implement early stopping?

**Comment by ppwwyyxx** [comment]
If you mean how to do early stopping when using detectron2's `Trainer`, you can implement a hook and in its `after_step`, raise an exception when you decide to exit.

**Comment by maxfrei750** [comment]
Thanks for the quick reply. I think hook-wise, I found all the things I am going to need. However, raising an exception to interrupt the training seems a little violent to me. What would be the best way to stop the training, while still having it terminate gracefully (i.e. writing all the logs, saving the last checkpoint, doing evaluation, etc.)?

**Comment by ppwwyyxx** [comment]
One basic assumption of the hook system is that hooks are independent, so it's not easy to make the behavior of one hook depend on others. In general it's also good to use custom training loop when you need complicated control flows.

One way to achieve what you described with the hook system is to make logging/checkpointing hooks perform its action in `after_train()` when they detect that they did not get the chance to execute the last `after_step` (due to unexpected termination).
