### ISSUE TITLE
Video Detection with Custom Trained Model

### ISSUE THREAD

**Issue by huangl6** [facebookresearch/detectron2#532]
1. what changes you made (`git diff`) or what code you wrote
2. what exact command you run:
I used this command to try and run video inference using the code in demo,py:

!cd detectron2_repo && python demo/demo.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --video-input ../video-clip.mp4 --confidence-threshold 0.6 --output ../video-output.mkv \
  --opts MODEL.WEIGHTS ../gdrive/My\ Drive//Models/model_final.pth

3. what you observed (including the full logs):
Output video has no bounding boxes drawn. However, I was able to confirm that the custom trained model atleast works well on randomly selected images. The input video was downloaded from YouTube (as per the demo).

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

I suspect I am using the command line incorrectly. Any suggestions would be welcome. Thanks!

**Comment by ppwwyyxx** [comment]
Please include
> what you observed (including the full logs):

The simplest way to know whether your command line is correct is to use a model zoo model.

**Comment by huangl6** [comment]
Sorry here is the output: 

Failed to load OpenCL runtime
[12/15 09:28:51 detectron2]: Arguments: Namespace(confidence_threshold=0.7, config_file='configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', '../gdrive/My Drive/Samscloud/Models/model_final.pth'], output='../video-output.mkv', video_input='../video-clip.mp4', webcam=False)
WARNING [12/15 09:28:51 d2.config.compat]: Config 'configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
'roi_heads.box_predictor.cls_score.weight' has shape (2, 1024) in the checkpoint but (81, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (2,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (4, 1024) in the checkpoint but (320, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (4,) in the checkpoint but (320,) in the model! Skipped.
100% 361/361 [01:00<00:00,  6.01it/s]

**Comment by ppwwyyxx** [comment]
> 'roi_heads.box_predictor.cls_score.weight' has shape (2, 1024) in the checkpoint but (81, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (2,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (4, 1024) in the checkpoint but (320, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (4,) in the checkpoint but (320,) in the model!

It means you've modified the config when training the model but you used the original config for inference.

**Comment by huangl6** [comment]
Oh so in demo.py's setup_cfg function, I basically just paste the config setup I used to train the model?

**Comment by ppwwyyxx** [comment]
You can modify the config either in the code or in the command line.

**Comment by Surya20794** [comment]
In output video no object detection found . Giving same command .

!git clone https://github.com/facebookresearch/detectron2
!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --output video-output.mkv \
--opts MODEL.WEIGHTS /content/output/model_final.pth

**Comment by Surya20794** [comment]
fatal: destination path 'detectron2' already exists and is not an empty directory.
Failed to load OpenCL runtime
[06/25 04:12:07 detectron2]: Arguments: Namespace(confidence_threshold=0.6, config_file='detectron2/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml', input=None, opts=['MODEL.WEIGHTS', '/content/output/model_final.pth'], output='video-output.mkv', video_input='video-clip.mp4', webcam=False)
[06/25 04:12:10 fvcore.common.checkpoint]: Loading checkpoint from /content/output/model_final.pth
WARNING [06/25 04:12:10 fvcore.common.checkpoint]: Unable to load 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (4, 2048) in the checkpoint but (81, 2048) in the model!
WARNING [06/25 04:12:10 fvcore.common.checkpoint]: Unable to load 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (4,) in the checkpoint but (81,) in the model!
WARNING [06/25 04:12:10 fvcore.common.checkpoint]: Unable to load 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (12, 2048) in the checkpoint but (320, 2048) in the model!
WARNING [06/25 04:12:10 fvcore.common.checkpoint]: Unable to load 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (12,) in the checkpoint but (320,) in the model!
[06/25 04:12:10 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  roi_heads.box_predictor.bbox_pred.{weight, bias}
  roi_heads.box_predictor.cls_score.{bias, weight}
100% 181/181 [01:57<00:00,  1.54it/s]

**Comment by FirasAbdennadher** [comment]
@ huangl6 did u solved the problem?
