### ISSUE TITLE
Is there a way to draw the class with the highest score in case of overlap?

### ISSUE THREAD

**Issue by isagastiberri** [facebookresearch/detectron2#553]
## ❓ Is there a way to draw the class with the highest score in case of overlap?

Hi! I'm testing several networks in detectron2 and I also trained my own and I noticed something. If I test the pretrained network for panoptic and put the score threshold to 0, when drawing the predictions there is no overlapping in the instances that are drawn in the image. I mean, it returns about 100 instances for the image but it doesn't draw them all and it seems like in case of overlap of two instance predictions, it automatically draws the one that has the highest score.

When I draw the predictions of my own network it draws all of the predicted instances , regardless of score. So, some wrong instances that have a low score are drawn over the good ones with a highest score. I can't find the way to draw the instance with highest score in case of overlap but by the behavior of the visualization with the demo code it seem like it should be there. The function I'm using is **draw_instance_predictions**.

Thanks a lot

**Comment by ppwwyyxx** [comment]
Panoptic segmentation and instance segmentation have different visualization logic. What you described seems an expected behavior: in instance segmentation it always draws larger ones first.

What makes a nice visualization is a subjective thing. If you don't like the current one, you can implement a different visualization logic.

**Comment by isagastiberri** [comment]
okay, perfect! I just wanted to check. Thanks for the answer
