### ISSUE TITLE
Feature: Scale-aware Training Scheme for TridentNet

### ISSUE THREAD

**Issue by xmyqsh** [facebookresearch/detectron2#595]
## 🚀 Feature

Scale-aware Training Scheme

## Motivation

Why TridentNet called **Scale-aware** Trident Network for Object Detection?
Not only because of the TridentBlock, but also the Scale-aware Training Scheme.
You cannot get **48.4 AP** without the Scale-aware Training Scheme.

Remember: [Image Pyramid](https://github.com/facebookresearch/detectron2/blob/master/projects/TridentNet/configs/Base-TridentNet-Fast-C4.yaml#L28) always be company with Scale-aware Training Scheme.

**Comment by ppwwyyxx** [comment]
The improvement from the scale-aware training scheme is actually not large according to the paper. 
In general we do not consider large feature requests for `projects/` directory since they are research projects, and their development prioritizes on our research needs.
Since this is a new training scheme, implementing it will require significant amount of new code. So it's unlikely any maintainers will spend time doing it unless it becomes important for our research at some day.
