### ISSUE TITLE
train video dataset in detectron2

### ISSUE THREAD

**Issue by yustaub** [facebookresearch/detectron2#919]
## ❓ How to use Detectron2

1. How to do train video dataset with detectron2?
I have a video dataset  and its json file, each frame there is one  plane, and the json file include "exist" and "gt_rect", can I use detectron2 to train this video dataset?

**Comment by ppwwyyxx** [comment]
You can train a model on your dataset following https://detectron2.readthedocs.io/tutorials/datasets.html.

**Comment by yustaub** [comment]
@ppwwyyxx should I process the video to picture dataset firstly? this is the first time that I train to the video dataset

**Comment by koon-ntu** [comment]
@yustaub If you don't want to convert the video to image files first, you can create a custom DataLoader and use dataset_dict["file_name"] to point to a specific frame on in your video file. Then, you can read that frame directly to the memory without intermediate image files.
https://detectron2.readthedocs.io/tutorials/data_loading.html

**Comment by mikeyEcology** [comment]
What if you want to use videos for training and leverage the temporal order of the frames? I'm trying to train a model to detect something small that can only be seen by looking at a video. There is a great example on how to train a model on images [here](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5), but I'm wondering how to incorporate videos in training instead of images.
