### ISSUE TITLE
Implement visualize_training as a Hook instead of as a method of RetinaNet

### ISSUE THREAD

**Issue by mnslarcher** [facebookresearch/detectron2#947]
## 🚀 Feature
Move the `visualize_training` logic outside RetinaNet in a `Hook `reusable also by others `meta_arch`.

## Motivation

I think that visualization of images with predicted and ground truth boxes is not specific of RetinaNet and can be beneficial also for others architectures. Probably is possible to reproduce the same functionality with a `Hook`. I also think that if this is possible, it will be probably easier in this way to extend the current solution and to increase the reuse of the code.

## Pitch

I imagine a `Visualizer` hook that, based on the task and some configuration, can be used in different situations.

**Comment by ppwwyyxx** [comment]
>  visualization of images with predicted and ground truth boxes is not specific of RetinaNet

This is true. However there are also many potential issues doing something like this:

1. it is very possible that each model will do visualization that's specific to the model, rather than just showing ground truth and predictions. Showing gt and predictions is the simplest form of visualization and is what is now implemented in RetinaNet, but models like R-CNNs already have more complicated visualizations built into it. Having the visualization logic inside model is more friendly to future types of visualizations that require intermediate results in addition to just the groundtruth and predictions.

2. the model only computes losses during training. Implementing a hook requires a way to "tell the model to return other things needed for visualization" - which would require new designs.

The easiest way to "increase the reuse of the code" as you suggest, seems to be just making the visualization logic in RetinaNet a utility function so other models, if needed, can use it. Implementing a hook does not seem like a practical solution now for reasons above. If you have concrete design proposals you can bring them up for discussion.

**Comment by ppwwyyxx** [comment]
Or another perhaps reasonable option is to do it in inference mode, with a simple function like `visualize_predictions(data_loader, model)`. It will happen independently from the training - so is slightly more compute cost and is not consistent with how some of the training-time visualizations are made. But this would work for all models with similar inputs/outputs format.

**Comment by mnslarcher** [comment]
> Or another perhaps reasonable option is to do it in inference mode, with a simple function like `visualize_predictions(data_loader, model)` called once a while. Maybe this is what you had in mind?
> It will happen independently from the training - so is slightly more compute cost and is not consistent with how some of the training-time visualizations are made. But this would work for all models with similar inputs/outputs format.

Premise: it is only a couple of days that I have been learning to use detectron2, probably many things that I say make no sense.

Said this, I said a hook because, from a user point of view this
```python
class Visualizer(HookBase):
    def __init__(self, data_loader):
[some logic here]
```
means that I can simply register my hook passing a data loader to it and I'm done.

In my understanding, the `model` argument is not needed in this case because I can access it from `self.trainer.model`.

I suspect that to use `visualize_predictions(data_loader, model)` in inference mode the user also need to modify the training logic (but again, probably I'm wrong).

In general, seems nice to use hooks for all the stuff that write something to TensorBoard and to separate the visualization from the architecture itself.

But yes, both the hook and the function would be less efficient that the current implementation (but probably more flexible, for example I can use a data_loader with validation images, I can create multiple Hooks and let the user decide which one to use, I can add more parameters without using cfg etc.).
