### ISSUE TITLE
Publish on PyPi

### ISSUE THREAD

**Issue by billop** [facebookresearch/detectron2#969]
## 🚀 Feature

I propose that detectron2 be published on PyPi so that it can be installed via `pip install detectron2` and can be tracked by dependency managers such as poetry.

## Motivation

Although pycocotools on pypi is still broken, it would simplify the installation process of detectron2 and also allow it to be installed from a lock file tracking exact versions and hashes, increasing reproducibility.

**Comment by ppwwyyxx** [comment]
You can already install detectron2 package following https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#install-pre-built-detectron2. Not on PyPI.

> can be tracked by dependency managers such as poetry.
> allow it to be installed from a lock file tracking exact versions and hashes

These are not true. Because users have to select detectron2 with the correct cuda version. Putting it in a dependency file will only make users more likely to install a wrong version.
